import random
import copy
from app.Problem.Individual import *
from app.Utilities.EALogger import *
from app.OptimizationAlgorithm.OptimizationAlgorithm import *

class EvolutionaryAlgorithm(OptimizationAlgorithm):
    def __init__(self, problem, pop_size=100, generations=100, tour_size=5, px=0.7, pm=0.1, mutation='swap', crossover='ox',elitism_size=0):
        super().__init__(problem) # constructor of the mother class
        #self.problem = problem
        self.pop_size = pop_size  # size of the population
        self.generations = generations # number of generatio,
        self.tour_size = tour_size # size of the tournament
        self.px = px # crossover probability
        self.pm = pm # mutation probability
        self.population = []
        self.logger = EALogger() # for log the results of each generation
        self.crossover = crossover
        self.mutation = mutation
        self.elitism_size = elitism_size

    def initialize_population(self):
        """Initialize the population randomly."""
        self.population = []
        for _ in range(self.pop_size):
            seq = list(range(self.problem.num_jobs))
            random.shuffle(seq)
            ind = Individual(seq)
            ind.evaluate(self.problem)
            self.population.append(ind)

    def tournament_selection(self):
        """Selection by tournament: chose the best among N individuals selected at random."""
        participants = random.sample(self.population, self.tour_size)
        best = min(participants, key=lambda x: x.fitness)
        return copy.deepcopy(best)

    def crossover_ox(self, parent1, parent2):
        """
        Ordered Crossover OX.
        Selects a subsequence from parent 1 and copies it into the child.
        Fills in the rest with genes from parent 2, preserving their order.
        Returns two children by swapping the roles of the parents.
        """
        size = len(parent1.sequence)
        
        def generate_child(p1, p2):
            # Select two random cut points
            start, end = sorted(random.sample(range(size), 2))
            
            # Copy the subsequence of the first parent
            child_seq = [None] * size
            child_seq[start:end+1] = p1.sequence[start:end+1]
            
            # Fill the remaining positions with elements from p2
            # We retrieve the elements from p2 that are not yet in the child
            p2_filtered = [gene for gene in p2.sequence if gene not in child_seq]
            
            # Enter these items from left to right in the “None” fields
            p2_idx = 0
            for i in range(size):
                if child_seq[i] is None:
                    child_seq[i] = p2_filtered[p2_idx]
                    p2_idx += 1
                    
            return Individual(child_seq)

        # We create two children by reversing the order of the parents
        child1 = generate_child(parent1, parent2)
        child2 = generate_child(parent2, parent1)
        
        return child1, child2
    
    def crossover_pmx(self, parent1, parent2):
        """
        Partially Mapped Crossover PMX.
        Copies a subsequence from one parent and fills the rest from the other parent,
        using a mapping relationship to resolve duplicated jobs.
        """
        size = len(parent1.sequence)
        
        def generate_child(p1, p2):
            start, end = sorted(random.sample(range(size), 2))
            child_seq = [None] * size
            
            # Copy the mapping's section from p2
            child_seq[start:end+1] = p2.sequence[start:end+1]
            
            # Create the correspondance dictionary (mapping) : p2_val -> p1_val
            mapping = {}
            for i in range(start, end+1):
                mapping[p2.sequence[i]] = p1.sequence[i]
                
            # Fill the rest with p1
            for i in range(size):
                if start <= i <= end:
                    continue # ignoring the copied subsequence
                
                val = p1.sequence[i]
                #if there's an issue (number in the copied subsequence), we replace it using dico
                while val in mapping:
                    val = mapping[val]
                
                child_seq[i] = val
                
            return Individual(child_seq)

        # we create O1 (p1 with the subsequence of p2) and O2 (p2 with the subsequence of p1)
        child1 = generate_child(parent1, parent2)
        child2 = generate_child(parent2, parent1)
        
        return child1, child2
    
    def crossover_cx(self, parent1, parent2):
        """
        Cycle Crossover CX.
        Finds a cycle between parents starting from the first element.
        Copies the cycle from parent 1 to child 1, and fills the rest with parent 2.
        Child 2 is generated by swapping the roles of the parents.
        """
        size = len(parent1.sequence)

        def generate_child(p1, p2):
            child_seq = [None] * size
            
            # we start the cyle at the indice 0
            start_idx = 0
            curr_idx = start_idx
            
            # we continue the cycle until we reach the starting point
            while True:
                # we copy the task of parent 1
                child_seq[curr_idx] = p1.sequence[curr_idx]
                
                # we get the task at this position of parent 2
                val_in_p2 = p2.sequence[curr_idx]
                
                # we search the corresponding indice in the parent 1
                curr_idx = p1.sequence.index(val_in_p2)
                
                # if we get back to the starting point, the cycle is finished
                if curr_idx == start_idx:
                    break
                    
            # we fill the gaps with parents 2
            for i in range(size):
                if child_seq[i] is None:
                    child_seq[i] = p2.sequence[i]
                    
            return Individual(child_seq)

        # we generate the two offsprings
        child1 = generate_child(parent1, parent2)
        child2 = generate_child(parent2, parent1)
        
        return child1, child2

    def mutate_swap(self, individual):
        """Mutation Swap : swaps the positions of two random tasks."""
        if random.random() < self.pm:
            idx1, idx2 = random.sample(range(len(individual.sequence)), 2)
            individual.sequence[idx1], individual.sequence[idx2] = individual.sequence[idx2], individual.sequence[idx1]

    def mutate_inversion(self, individual):
        """Inversion: Reverses the order of a random subsequence."""
        if random.random() < self.pm:
            idx1, idx2 = sorted(random.sample(range(len(individual.sequence)), 2))
            individual.sequence[idx1:idx2+1] = reversed(individual.sequence[idx1:idx2+1])

    def run(self):
        """Run the EA."""
        self.initialize_population()

        '''We disabled logger to run experiment faster !!'''
        #self.logger = EALogger() # initialize the logger at the beginning
        
        best_overall = copy.deepcopy(min(self.population, key=lambda x: x.fitness))

        '''We disabled logger to run experiment faster !!'''
        # Log generatio n0
        #self.logger.log_generation(0, self.population)
        
        for gen in range(1, self.generations + 1):
            new_population = []

            # elitism feature
            if self.elitism_size > 0:
                # we sort the actual population from better to worse
                self.population.sort(key=lambda x: x.fitness)
                
                # we deepcopy the'elitism_size' best in the new generation
                for i in range(self.elitism_size):
                    new_population.append(copy.deepcopy(self.population[i]))
            
            while len(new_population) < self.pop_size:
                # selection
                p1 = self.tournament_selection()
                p2 = self.tournament_selection()
                
                # Crossover
                if self.crossover == 'ox':
                    if random.random() < self.px:
                        c1, c2 = self.crossover_ox(p1, p2)
                    else:
                        c1, c2 = copy.deepcopy(p1), copy.deepcopy(p2)
                elif self.crossover == 'pmx':
                    if random.random() < self.px:
                        c1, c2 = self.crossover_pmx(p1, p2)
                    else:
                        c1, c2 = copy.deepcopy(p1), copy.deepcopy(p2)
                elif self.crossover == 'cx':
                    if random.random() < self.px:
                        c1, c2 = self.crossover_cx(p1, p2)
                    else:
                        c1, c2 = copy.deepcopy(p1), copy.deepcopy(p2)
                else:
                    print('Crossover not defined, using ox by default')
                    if random.random() < self.px:
                        c1, c2 = self.crossover_ox(p1, p2)
                    else:
                        c1, c2 = copy.deepcopy(p1), copy.deepcopy(p2)
                
                # Mutation
                if self.mutation == 'swap':
                    self.mutate_swap(c1)
                    self.mutate_swap(c2)
                elif self.mutation == 'inversion':
                    self.mutate_inversion(c1)
                    self.mutate_inversion(c2)
                else:
                    print("Mutation not defined, using swap by default...")
                    self.mutate_swap(c1)
                    self.mutate_swap(c2)
                
                # Evaluation
                """NOTE : TO DO BUFFER THE LAST POPULATION AND CHECK BEFORE EVALUATE AGAIN"""
                c1.evaluate(self.problem)
                c2.evaluate(self.problem)
                
                new_population.extend([c1, c2])
                
            # Replacement
            self.population = new_population[:self.pop_size]
            
            '''We disabled logger to run experiment faster !!'''
            # Saving the stats of the current generation
            #self.logger.log_generation(gen, self.population)

            # At the genereation's end, we update the best overall if needed
            current_best = min(self.population, key=lambda x: x.fitness)
            if current_best.fitness < best_overall.fitness:
                best_overall = copy.deepcopy(current_best)
            
        # display the best overall
        #best_overall = min(self.population, key=lambda x: x.fitness)
        #print(f"End of the evolution, best found: {best_overall.fitness}")

        #print(min(self.population, key=lambda x: x.fitness).fitness)
        #return min(self.population, key=lambda x: x.fitness)
        
        return best_overall
        
